### ISSUE TITLE
Allow access to internal docker registry via docker CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/docker-registry#38]
**Description**
Expose docker registry in a way so that it is accessible via docker CLI push command.
Guide user how to configure docker CLI in order to allow accessing kyma's internal docker registry.
Provide necessary kyma cli command to expose docker registry and instruct user how to configure `~/.docker/config.json`
 

**Reasons**
Developers are used to docker CLI in their daily work. Making it possible to push docker images into kyma's internal docker registry via `docker push` command would go hand in hand with a commonly adopted dev experience.

**Attachments**

https://docs.docker.com/engine/reference/commandline/cli/#docker-cli-configuration-file-configjson-properties

**Comment by pPrecel** [comment]
I've tested a bit of registry port-forwarding:

```bash
kubectl port-forward -n kyma-system  svc/dockerregistry 5002:5000
```

I see two ways to reach the registry server:
- by the `HTTP` protocol -> to force the HTTP protocol we need to use the localhost address. for example: `docker push localhost:5002/test-sleep:0.2`
- by the `HTTPS` protocol -> to call it like that we need to put server address/ip in the cli command. for example `docker push 0.0.0.0:5002/test-sleep:0.2`

In both solution we need to face problems:

* The `HTTPS` protocol right now is not supported and it's described in [this ticket](https://github.com/kyma-project/docker-registry/issues/37). Actual output:

  ```
  docker push 0.0.0.0:5002/test-sleep:0.2
  
  The push refers to repository [0.0.0.0:5002/test-sleep]
  Get "https://0.0.0.0:5002/v2/": http: server gave HTTP response to HTTPS client
  ```

* The `HTTP` protocol is fully supported right now, but docker-cli is not compatible with the `kubectl port-forward` command and we need to investigate and face the following error:

  ```
  docker push localhost:5002/test-sleep:0.2
  
  The push refers to repository [localhost:5002/test-sleep]
  Get "http://localhost:5002/v2/": dial tcp [::1]:5002: connect: connection refused
  ```

**Comment by kwiatekus** [comment]
Depends on #37
