### ISSUE TITLE
Use NFS Storage as a backend storage for docker registry

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/docker-registry#51]
**Description**
Use NFS Storage as a backend storage for docker registry

**AC** 
 - [ ] User can configure a docker registry storage using an NFS storage class via DockerRegistry CR
 - [ ] User can deduct that a NFS storage is used based on the docker registry status
 - [ ] Document how to configure NFS storage as a backend for docker registry ( incl prerequisite: link to cloud manager tutorial)  
 - [ ] Operator should resolve CR into warning state in case reference storage class doesnt exist on the cluster

**Test Strategy**
Full integration test incl. cloud manager should be performed manually.
A new unit test should be added (testing which flags are passed to the helm chart based on DockerRegistry CR).

**Reason**
Using Network File System Storage class will be a great addition to the already provided storage options of docker registry.
When mounted into docker registry pod, it could serve as a highly available storage resource, the content of which is not purged upon unmounting.

**Attachments**
https://kubernetes.io/docs/concepts/storage/volumes/#nfs
https://github.com/kyma-project/cloud-manager/blob/main/docs/user/README.md#features
https://github.com/kyma-project/cloud-manager/tree/main/docs/user/tutorials

**Comment by halamix2** [comment]
We'll support nfs through PersistentVolumeClaim, as there is an existing support for providing existing PVC; and also because pvc supports more storage options than just nfs

**Comment by kwiatekus** [comment]
@halamix2 When reviewing the implementation I would like to request the follwowing:
 - Please add a reference to the used PVC in the docker-registry's status
 - Please add a section regarding NFS storage to the user guide [here](https://github.com/kyma-project/docker-registry/blob/main/docs/user/00-30-storage-configuration.md)
