### ISSUE TITLE
Mark tests required

### ISSUE THREAD

**Issue by halamix2** [kyma-project/docker-registry#75]
**Description**

Currently tide will merge PR even if tests have failed. 

We need to change that by
- changing tests to always run (remove `paths-ignore`, `paths` configs ), moving trigger conditions to a step
- marking tests required in branch protection

**AC**
 - block merging if one of the following fails:
   - [ ] build jobs
   - [ ] linter
   - [ ]  unit tests
   - [ ] integration tests
   - [ ] image tag checker - [`images verify`](https://github.com/kyma-project/serverless/blob/main/.github/workflows/images-verify.yaml) (only in serverless)
 - allow merging when link checker fails

**Execution**
 - [x] serverless - @pPrecel 
 - [x] docker registry
 - [x] keda 
 - [x] warden

**Attachments**
https://docs.github.com/en/enterprise-server@3.11/actions/using-workflows/required-workflows

**Comment by pPrecel** [comment]
All of our tests have the `paths-ignore` configuration that allows us to push changes to the documentation without running and waiting for tests:

```yaml
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
```

We need to discuss what we expect regarding this configuration. If we want to mark tests as required, we need to run tests on every change.
