### ISSUE TITLE
Expose docker registry CR configuration in kyma dashboard

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/docker-registry#95]
**Description**

Configure views (list, details, form) for docker registry so that kyma dashboard can render ui components allowing the users to inspect (spec and status) and modify docker registry spec.

**AC**
 Kyma dashboard user can:
  - [x] navigate to docker registry details from a list of kyma modules 
  - [x] view the docker registry desired configuration (incl. external access config and storage backend config )
  - [x] view the actual applied configuration (from status: incl. external access config and storage backend config )  
  - [x] edit the desired specification  (incl. external access config and storage backend config ):
  - [x] select existing secrets (lookup) when referencing them in the docker registry config
  - [x] pre-select storage provider (via dropdown) and should see only relevant config options per storage provider

**Testing strategy**

Listing/Viewing/Editing docker registry config via kyma dashboard should be tested manually as we don't have yet automated tests for our ui components

**Reasons**

All the configurability options of docker registry module should be exposed in kyma dashboard to ensure a complete user experience.
 
**Attachments**
https://github.com/kyma-project/busola/tree/main/docs/extensibility
[Our ui config resources](https://github.com/kyma-project/docker-registry/tree/main/config/operator/base/ui-extensions/dockerregistry)

**Comment by halamix2** [comment]
Edit/form part is implemented in #150

As to desired/actual state it's not implemented this way, it might need to be adjusted (in the details section)
